### ISSUE TITLE
Not working with laravel 5.7

### ISSUE THREAD

**Issue by MiticoBerna** [SeBuDesign/Laravel-POEditor#1]
Hi Sven Buijsrogge,

due to some requires in composer.json like

```
"illuminate/container": "~5.3.0|~5.4.0|~5.5.0|~5.6.0",
"illuminate/contracts": "~5.3.0|~5.4.0|~5.5.0|~5.6.0",
"illuminate/database": "~5.4.0|~5.5.0|~5.6.0"
```

it's not possible to install if the app is on laravel 5.7 or higher.

Could you fix this please?

Thanks

**Comment by svennis94** [comment]
Added 5.7 to the composer.json in 1.2.1
